src/Entity/Message.php
<?php

namespace App\Entity;

use App\Entity\Traits\TimestampableTrait;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message
{

    use TimestampableTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messages")
     * @MaxDepth(2)
     * @ORM\JoinColumn(nullable=false)
     * @Groups({"default"})
     */
    private $senderId;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messages")
     * @ORM\JoinColumn(nullable=true)
     * @MaxDepth(3)
     * @Groups({"default"})
     */
    private $receiverId;

    /**
     * @ORM\Column(type="text")
     * @Groups({"default"})
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Groupe", inversedBy="messages")
     */
    private $groupeId;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSenderId(): ?User
    {
        return $this->senderId;
    }

    public function setSenderId(?User $senderId): self
    {
        $this->senderId = $senderId;

        return $this;
    }

    public function getReceiverId(): ?User
    {
        return $this->receiverId;
    }

    public function setReceiverId(?User $receiverId): self
    {
        $this->receiverId = $receiverId;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getGroupeId(): ?Groupe
    {
        return $this->groupeId;
    }

    public function setGroupeId(?Groupe $groupeId): self
    {
        $this->groupeId = $groupeId;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Traits\SortablePositionTrait;
use App\Entity\Traits\TimestampableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="user_account")
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    use TimestampableTrait;
    use SortablePositionTrait;

    const GENDER = [
        'homme' => 'm',
        'femme' => 'f',
        'autre' => 'a'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"default"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     * @Assert\Expression("this.getLastname() != this.getFirstname()", message="Prénom et nom identique")
     * @Groups({"default"})
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     */
    private $firstname;

    /**
     * @Gedmo\Slug(fields={"firstname", "lastname"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetimetz", nullable=true)
     */
    private $birthday;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="createdBy")
     */
    private $articles;

    /**
     * @ORM\Column(type="string", length=1)
     * @Assert\Choice(choices=User::GENDER)
     */
    private $gender;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @var string plainPassword
     */
    private $plainPassword;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Image(maxSize="2M", mimeTypes={"image/png", "image/jpeg"}, maxHeight="300", maxWidth="300", maxRatio="100")
     */
    private $avatar;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="userId")
     */
    private $posts;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="userId")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="senderId")
     * @MaxDepth(2)
     */
    private $messages;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Groups({"default"})
     */
    private $imageFileName;

    public function getImageFilename()
    {
        return $this->imageFileName;
    }

    public function setImageFilename($imageFileName)
    {
        $this->imageFileName = $imageFileName;

        return $this;
    }

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Groups({"default"})
     */
    private $backgroundImageFileName;

    public function getBackgroundImageFileName()
    {
        return $this->backgroundImageFileName;
    }

    public function setBackgroundImageFileName($backgroundImageFileName)
    {
        $this->backgroundImageFileName = $backgroundImageFileName;

        return $this;
    }

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="friends")
     */
    private $friends;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Groupe", mappedBy="users", cascade={"persist"})
     */
    private $groupes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Event", mappedBy="creator", orphanRemoval=true)
     */
    private $events;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Event", mappedBy="attenders")
     */
    private $linkedEvents;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->friends = new ArrayCollection();
        $this->groupes = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->linkedEvents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }


    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setCreatedBy($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getCreatedBy() === $this) {
                $article->setCreatedBy(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * @param mixed $lastname
     * @return User
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * @param mixed $firstname
     * @return User
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     * @return User
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * @param mixed $birthday
     * @return User
     */
    public function setBirthday($birthday)
    {
        $this->birthday = $birthday;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * @param mixed $gender
     * @return User
     */
    public function setGender($gender)
    {
        $this->gender = $gender;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * @param mixed $avatar
     * @return User
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;
        return $this;
    }

    /**
     * @return string
     */
    public function getPlainPassword():? string
    {
        return $this->plainPassword;
    }

    /**
     * @param string $plainPassword
     * @return User
     */
    public function setPlainPassword(string $plainPassword):? User
    {
        $this->plainPassword = $plainPassword;
        return $this;
    }

    public function getfullName()
    {
        return $this->getLastname() . ' ' . $this->getFirstname();
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setUserId($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getUserId() === $this) {
                $post->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('content', TextareaType::class, [
                'attr' => ['class' => 'textareaDefault']
            ])
            ->add('Envoyer',
                SubmitType::class,
                ['attr' => ['class'=>'save defaultButton validateButton']]
            )

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/Front/DefaultController.php
<?php

namespace App\Controller\Front;

use App\Entity\Comment;
use App\Entity\Post;
use App\Entity\Tag;
use App\Form\CommentType;
use App\Form\PostType;
use App\Service\NotificationService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mercure\Update;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class DefaultController
 * @package App\Controller\Front
 */
class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="default_index", methods={"GET","POST"})
     */
    public function index(Request $request, MessageBusInterface $bus, MailerInterface $mailer, NotificationService $notification): Response
    {
        $comment = new Comment();
        $post = new Post();
        $user = $this->getUser();
        $requestData = $request->request->all();

        if (isset($requestData["postId"])) {
            $form = $this->createForm(CommentType::class, $comment);
            $form->handleRequest($request);
            // Check if the form is valid
            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $post = $this->getDoctrine()->getRepository(Post::class)->find($requestData["postId"]);
                $comment->setPostId($post);
                $comment->setUserId($user);
                $entityManager->persist($comment);
                $entityManager->flush();

                return $this->redirectToRoute('post_show', [
                    'id' => $post->getId(),
                ]);
            }
        } else {
            $form = $this->createForm(PostType::class, $post);
            $form->handleRequest($request);
            // Check if the form is valid
            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                // Get tags and save them
                $postContent = $post->getContent();
                preg_match_all("~#[a-z]*( |$)~", $postContent, $tags);
                $tags = $tags[0];

                for($j = 0; $j < sizeof($tags); $j++){
                    $tagName = $tags[$j];
                    $tagName = substr($tagName, 1);
                    $tag = new Tag();
                    $tag->setName($tagName);
                    $tag->addPostId($post);
                    $entityManager->persist($tag);
                    $post->addTag($tag);
                }

                $post->setUserId($user);
                $entityManager->persist($post);
                $entityManager->flush();

                // Send notification to friends
                $friends = $user->getFriends();
                foreach ($friends as $friend) {
                    $id = $friend->getId();
                    dump("post/newPost/".$id);
                    $update = new Update("post/newPost/".$id,
                        json_encode(['message' => $user->getSlug().' a créer un nouveau post !'])
                    );
                    $bus->dispatch($update);
                }

                //return $this->redirectToRoute('default_index');
            }
        }
        $posts = $this->getDoctrine()->getRepository(Post::class)->findTenPost();

        // create postFrom
        $postForm = $this->createForm(PostType::class, $post);
        // create comment Form
        $data = [];
        for ($i = 0; $i < sizeof($posts); $i++) {
            $data[$i] = [];
            $data[$i]["post"] = $posts[$i];
            $form = $this->createForm(CommentType::class, $comment);
            $data[$i]["form"] = $form->createView();
        }

        return $this->render('front/user/show.html.twig', [
            'data' => $data,
            'postForm' => $postForm->createView(),
            'user' => $user
        ]);
    }
}

templates/front/message/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/front/message/discussion.html.twig
{% extends 'front.html.twig' %}
{% block title %}Messages{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('messages') }}
{% endblock %}
{% block body %}
    <h3 class="back-button"><a href="{{ app.request.headers.get('referer') }}">&#8678;</a></h3>
    <h2>{% if receiver is defined %} {{ receiver.lastname }}{% else %}{{ groupe.subject }}{% endif %}</h2>
    <input id="userId" type="hidden" value="{{user.getId()}}">
    {% if receiver is defined %}<input id="receiverId" type="hidden" value="{{receiver.getId()}}">{% endif %}
    {% if groupe is defined %}<input id="groupeId" type="hidden" value="{{groupe.getId()}}">{% endif %}
    <div id="containerDiscussion">
{#        <div class="sidebar">#}
{#            <a href="{{ path('message_index') }}">Retour à la liste</a>#}
{#        </div>#}
        <div id="messagerieContainer">
            <div id="messages">
                {% for message in messages %}
                    <div class="row  {% if message.senderId.getId() is same as(user.getId())  %}sender{% else %}receiver{% endif %}">
                        <div class="message">
                            <img class="profile-pic" src="{{ message.senderId.imageFilename }}" alt="Avatar">
                            <div class="line">
                                <div class="upperLine">
                                    <p class="userName"> {{message.senderId.getFirstname()}}</p> <p class="date" data-fulldate="{{ message.createdAt|date('m/d/Y H:i:s') }}">{{ message.createdAt|date('H:i:s') }}</p>
                                </div>
                                <div class="content">{{ message.content }}</div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div>
                        <p id="firstMessage">Envoyez un premier message !</p>
                    </div>
                {% endfor %}
            </div>
            {{ include('front/message/_form.html.twig') }}
        </div>

    </div>
{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('messages')}}
{% endblock %}

templates/front/message/discussionList.html.twig
{% extends 'front.html.twig' %}

{% block title %}Messages{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('discussionList') }}
{% endblock %}

{% block body %}
    <h2>Messages</h2>
    <div id="discussionListContainer">
        <section id="friendContainer" >
            <h3>Mes ami.e.s</h3>
            <form id="searchFriendForm" class="searchBar" autocomplete="off" action="">
                <div class="autocomplete" style="width:300px;">
                    <input id="inputFriends" class="inputDefault" type="text" name="myInput" placeholder="Rechercher un(e) ami(e)">
                </div>
                <a class="addButton defaultButton validateButton">Ajouter</a>
            </form>
            <div class="table-content-container">
                <table id="friendListTable" class="listTable">
                <thead>
                <tr>
{#                    <th></th>#}
{#                    <th align="center">Ami</th>#}
{#                    <th align="center">Rejoindre la discussion</th>#}
{#                    <th align="center">Retirer des ami.e.s</th>#}
                </tr>
                </thead>
                <tbody>
                {% for user in userFriends %}
                    <tr id="{{user.firstname}}_{{user.lastname}}">
                        <td align="center">
                                <img class="profile-pic" src="{{ asset(user.imageFilename) }}"/>
                        </td>
                        <td align="center">{{ user.lastname }}</td>
                        <td align="center">
                            <a class="joinDiscussion" href="{{ path('message_discussion', {'id': user.id}) }}">Rejoindre la discussion</a>
                        </td>
                        <td align="center"><a class="deleteButton" href="{{ path('user_friend_delete', {'id': user.id}) }}">X</a></td>
                    </tr>
                {% else %}
                    <tr>
                        <td></td>
                        <td colspan="3">Vous n'avez pas ajouté d'ami</td>
                        <td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
        </section>
        <section id="groupeContainer">
            <h3>Mes groupes</h3>
            <form id="searchGroupForm" class="searchBar" autocomplete="off" action="">
                <div class="autocomplete" style="width:300px;">
                    <input id="inputGroupes" class="inputDefault" type="text" name="myInput" placeholder="Rechercher un groupe">
                </div>
                <a class="addButton defaultButton validateButton">Rejoindre</a>
            </form>
            <div class="table-content-container">
                <table id="groupeListTable" class="listTable" >
                    <thead>
                    <tr>
{#                        <th>Groupe</th>#}
{#                        <th>Rejoindre la discussion</th>#}
{#                        <th>Quitter le groupe</th>#}
                    </tr>
                    </thead>
                    <tbody>
                    {% for group in groupsOfUser %}
                        <tr>
                            <td align="center">{{ group.subject }}</td>
                            <td align="center">
                                <a href="{{ path('message_discussion_group', {'id': group.id}) }}">Rejoindre la discussion</a>
                            </td>
                            <td align="center"><a class="deleteButton" href="{{ path('user_leave_groupe', {'id': group.id}) }}">X</a></td>
                        </tr>
                    {% else %}
                        <tr>
                            <td></td>
                            <td colspan="3">Vous n'avez pas rejoint de groupe.</td>
                            <td></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </div>

    <script>

        window.users = [
            {% for user in users %}
            {
                "userId": "{{ user.id }}",
                "lastname": "{{ user.lastname }}"
            },
            {% else %}
            {'none': 'none'},
            {% endfor %}
        ];

        window.groupes = [
            {% for group in groupes %}
            {
                "groupeId": "{{ group.id }}",
                "subject": "{{ group.subject }}"
            },
            {% else %}
                {'none': 'none'},
            {% endfor %}
        ];

    </script>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('discussionList') }}
{% endblock %}